### ISSUE TITLE
Add array-based include support

### ISSUE THREAD

**Issue by barneywilliams** [ThrowTheSwitch/yaml_extras#1]
It would be handy to be able to include a given YAML submodule, but then after the fact override or merge in additional items. The proposed implementation is to allow the INCLUDE to be an array, and the inclusion of each file is done sequentially per specified ordering of array.

Would also be convenient to be able to specify the secondary items to merge into the base submodule verbatim instead of need to specify a separate file for overriding just 1 or 2 simple elements. Not sure it this would be feasible nor am I sure how that would be specified in the master YAML file.

**Comment by sw17ch** [comment]
Is this an appropriate example for the first issue?

### main.yml

``` yaml
---
INCLUDE:
  - first_include.yml
  - second_include.yml
  - third_include.yml
```

### first_include.yml

``` yaml
---
a: 1
b: 2
c: 3
```

### second_include.yml

``` yaml
---
c: 5
d: 6
e: 7
```

### third_include.yml

``` yaml
---
e: 10
f: 11
g: 12
```

### combined.yml

``` yaml
---
a: 1
b: 2
c: 5
d: 6
e: 10
f: 11
g: 12
```
